# @file deploy/docker-compose.yml
# @brief Orchestrates Nginx service with secrets, read-only FS, tmpfs, and custom network
# @author Кочиев Георгий Джамболатович (kochiev@sfedu.ru)
# @date 2026-05-25
# @version 1.0.0
# @license MIT

services:
  nginx:
    build:
      context: ..
      dockerfile: deploy/docker/nginx/Dockerfile
    container_name: secure-nginx
    # Файловая система только для чтения
    read_only: true
    # Временные данные в RAM (требование read-only)
    tmpfs:
      - /var/cache/nginx:size=64m,uid=101,gid=101
      - /var/run:size=16m,uid=101,gid=101
      - /tmp:size=16m
    ports:
      - "80:80"
      - "443:443"
    # volumes с явными правами для локальной разработки
    volumes:
      - type: bind
        source: ../certs/server.crt
        target: /run/secrets/nginx_cert
        read_only: true
      - type: bind
        source: ../certs/server.key
        target: /run/secrets/nginx_key
        read_only: true
    networks:
      - frontend-net
    # Проверка жизнеспособности каждые 30с
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "https://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

# Секреты подтягиваются с хоста, но не попадают в слои образа
#secrets:
 # nginx_cert:
  #  file: ../certs/server.crt
  #nginx_key:
   # file: ../certs/server.key

# Изолированная сеть (без default bridge)
networks:
  frontend-net:
    driver: bridge
